name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write   # Needed to allow GitHub Actions to push to gh-pages

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      RUNNER: ${{ secrets.RUNNER }}
      TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

    steps:
    # Checkout the repo
    - uses: actions/checkout@v5

    # Setup Node.js
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Install Playwright browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Clean old allure results
    - name: Clean previous Allure results
      run: rm -rf allure-results allure-report

    # Run Playwright tests
    - name: Run Playwright tests
      run: npm run e2e:make-appoint

    # Install Allure CLI for report generation
    - name: Install Allure CLI
      run: npm install -D allure-commandline

    # Generate Allure report
    - name: Generate Allure Report
      run: npx allure generate allure-results --clean -o allure-report

    # Deploy Allure report to GitHub Pages
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
